### ISSUE TITLE
Question about DynamoDb

### ISSUE THREAD

**Issue by luisjdtt** [KBB99/ai-badbunny-langchain-agent#1]
Hi there! Your repo looks great! I was curious about how you're using DynamoDB with LangChain, and I think I have an idea. However, I wanted to ask you a couple of questions. From reading your code, I understand that you're using two DynamoDB tables, right? Also, correct me if I'm wrong, but I couldn't find where the messages are being saved. Does this happen automatically, or am I missing something?

**Comment by KBB99** [comment]
Hey Luis. Check out the [DynamoDBChatMessageHistory class](https://github.com/hwchase17/langchain/blob/master/langchain/memory/chat_message_histories/dynamodb.py) in Langchain. When you use ConversationBufferMemory or any of the others and specify DynamoDB memory, responses are automatically appended. Make sure you've cdk deployed and that your AWS credentials are correctly configured for it to work.

**Comment by luisjdtt** [comment]
Sorry for the late replay. Thanks, at the end I ended up using my own implementation!
